baseURL = "https://raphideb.github.io/"
languageCode = "en-us"
title = "crashdump"

enableMissingTranslationPlaceholders = true

# Required if you want to render robots.txt template
enableRobotsTXT = true
enableGitInfo = true

[taxonomies]
   tag = "tags"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[params.ui]
breadcrumb_disable = false
footer_about_enable = true
navbar_logo = true
navbar_translucent_over_cover_disable = false
sidebar_menu_compact = false
sidebar_search_disable = false
sidebar_menu_foldable = false
showLightDarkModeMenu = true

[params]
github_repo = "https://github.com/raphideb/raphideb.github.io"

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

[markup]
  [markup.highlight]
      style = "tango"
      noClasses = false

[markup.goldmark.renderer]
unsafe = true

[params.ui.readingtime]
enable = true

[params.drawio]
enable = true

[module]
[module.hugoVersion]
extended = true
min = "0.147.0"
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"

[[menu.main]]
    name = "Postgres documentation"
    weight = 10
    url = "https://www.postgresql.org/docs/"
    
[[menu.main]]
    name = "Oracle documentation"
    weight = 20
    url = "https://docs.oracle.com/en/database/oracle/oracle-database/index.html"

[[menu.main]]
    name = "Perplexity"
    weight = 30
    url = "https://www.perplexity.ai/"
